services:
  ai-shell-agent:
    build: .
    container_name: ai-shell-agent-container
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PORT=${PORT:-3000}
    ports:
      - '${PORT:-3000}:8000'
    volumes:
      - .cache/huggingface:/app/vllm-test/.cache/huggingface
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]